### ISSUE TITLE
Feature: Local Caching

### ISSUE THREAD

**Issue by imshentastic** [zoo-labs/zoo#100]
## Summary
Currently, refreshing the site resets everything because the Redux state gets reset with it. We can utilize Moralis's local storage hook (setAsyncStorage method I believe). Eventually we'd also want to create a user table that stores all of their info for a more robust data source, but this local storage object will allow us to pull the data very quickly. 

https://docs.moralis.io/users/current-user

We can see here that Brian did something similar for Alpha.zap, as a 'quick load', before updating the state via redis and blockchain calls
![image](https://user-images.githubusercontent.com/54114442/127377926-462d6ab4-3d14-4695-b8a5-f4c83535a9c2.png)

**Comment by CoryFlynn** [comment]
Closing because we are using Moralis instead
