### ISSUE TITLE
Add `AnimalDrop` contract to support configurable Animal drops

### ISSUE THREAD

**Issue by zeekay** [zoo-labs/zoo#11]
# AnimalDrop
- [x] `createDrop` should be able to create add new drop to `ZooMedia`
- [x] Should have configurable supply of `Egg` NFTs
- [x] User should be able to call `buyEgg` and purchase NFT with `ZOO` token
- [x] User should be able to call `hatchEgg` with token ID and burn egg, get randomized Animal NFT
- [x] User should be able to call `breedAnimals(animal1, animal2)` to create a `HybridEgg` NFT
- [x] User should be able to call `hatchEgg` with hybrid egg token ID, burn egg, get deterministic HybridAnimal NFT
- [x] Need to configure yield per Animal / Hybrid

# ZooMedia
- [x] Need to be able to mint Egg NFT
- [x] Need to be able to mint Animal NFT
- [x] Need to be able to mint HybridAnimal NFT
- [x] Need to be able to track ZOO yield earned by each NFT
- [x] User should be able to call `freeAnimal` to collect `ZOO` in each NFT

Finally, we need to ensure that these contracts are deployed along with the initial distribution of eggs and animals.

Additional work will be required to ensure all assets are uploaded to IPFS so they can be referenced from NFTs.

# List of all animals and animal Assets
https://cz-demo.herokuapp.com/data/img-test

# ZOO Yield Matrix
https://docs.google.com/spreadsheets/d/1lspcyOIsn9HKfkTmWGsHofZtMlwnMPMBD46286x2PBE/edit?usp=drive_web&ouid=105673222987770619823

# Zoo Whitepaper
https://cdn.discordapp.com/attachments/867495373832323082/867531383630069780/CryptoZoo_-_White_Paper_07152021.pdf

# Sketch of AnimalDrop contract
```solidity
contract AnimalSet is Ownable {
    using Counters for Counters.Counter;
    Counters.Counter private _setIDs;

    Data data;

    Animal[] animals;
    string name;
    string description;
    uint256 yield;
    uint256 boost;
    uint256 probability;

    constructor(
        string _name,
        string _description,
        Data _data,
        uint256 _yield,
        uint256 _boost,
        uint256 _probability
    ) {
        name = _name
        description = _description
        data = _data
        yield = _yield
        boost = _boost
        probability = _probability
    }
}

contract AnimalDrop is Ownable {
    constructor(
        AnimalClass[] distribution,
        string[] hybridNames,
        uint256[] yields,
        uint256 maxCap
    ) {
        require(
            hybridNames.length == yields.length,
            "The hybrids and the yields must be the same length to create the distribution mapping"
        );

        Generation memory generation;
        generation.distribution = distribution;

        mapping(string => uint256) hybrids;
        for (uint256 i = 0; i < hybridNames.length; i++) {
            hybrids[hybridNames[i]] = yields[i];
        }
        generation.hybridDistribution = hybrids;
        generation.maxCap = maxCap;

        this.generation = generation;
    }

    /**
      update distribution for any animal
    */
}
```

**Comment by superposition** [comment]
test

**Comment by superposition** [comment]
asdfa

**Comment by zeekay** [comment]
Some psuedocode:

```solidity

    // Available types
    enum Types {
        bytes base_egg_type = "E";
        bytes base_animal_type = "A";
        bytes hybrid_egg_type = "H";
        bytes hybrid_animal_type = "G";
    }

    // Mapping of ZooDrops to Drop contract addresses
    mapping (uint256 => address) public drops;
    using Counters for Counters.Counter;
    Counters.Counter private _dropIDs;

    // Should take drop configuration and add animals to ZOO
    function addDrop(string name) public onlyOwner returns (uint256, address) {
        dropID = _dropIDS.increment();

        ZooDrop memory drop = new ZooDrop(name);
        drops[dropID] = drop;

        return (dropID, drop.address);
    }

    // Mapping of token ID to NFT type
    mapping (uint256 => Type) public types;

    // Mapping of token ID to Egg
    mapping (uint256 => Egg) public eggs;

    // Mapping of token ID to Animal
    mapping (uint256 => Animal) public animals;

    // Mapping of token ID to Hybrids
    mapping (uint256 => Hybrid) public hybrids;

    // Mapping of token ID to Hybrid Eggs
    mapping (uint256 => HybridEgg) public hybridEggs;
```

**Comment by zeekay** [comment]
This is fully implemented now.
