### ISSUE TITLE
Show all yield per animal on bank page

### ISSUE THREAD

**Issue by zeekay** [zoo-labs/zoo#146]
On the old demo, we showed top earners per day, lets list top 10 NFTs by yield here.

![IMG_3474](https://user-images.githubusercontent.com/285707/127772822-03f19883-74e7-41e9-becc-71c985c9b186.jpeg)

**Comment by soft-top-notch** [comment]
The PR is created for this ticket: 
https://github.com/zoo-labs/zoo/pull/153
