### ISSUE TITLE
Feature: Optimistic rendering

### ISSUE THREAD

**Issue by zeekay** [zoo-labs/zoo#158]
To ensure a smooth experience for players we want to optimistically render Egg cards. When buying or breeding, we can use `call` then `send` on `buyEgg` and `hatchEgg`. The `call` method will let us return the token in advance of the `send` transaction being confirmed. We should show a timer (similar to cool off) while transaction confirms.

For Hatching, lets have the cards animate back and forth until they are ready to be hatched, then a 1.3x enlarge animation + glow to indicate that it's ready to be clicked, which will show animation and reveal the hatched animal.

Example of a new egg bought that loads in as 50% opacity while waiting for chain confirmation:
<img width="599" alt="Screen Shot 2021-08-04 at 2 20 52 PM" src="https://user-images.githubusercontent.com/285707/128233957-5775d5e5-260c-49ea-9187-47e64c694236.png">

**Comment by CharlieD724** [comment]
In the example above, the hatch prompt should not appear until confirmed on chain and ready to hatch.
