### ISSUE TITLE
Feature: Show multiples of same animal 

### ISSUE THREAD

**Issue by CoryFlynn** [zoo-labs/zoo#66]
## Problem
There are duplicates of the same animal in the animal slider

## Solution
There should be a counter in the top right corner of the animal card to display how many animals of that type we have.
Check the animal id to see if animals are the same 
![Screen Shot 2021-07-26 at 2 32 00 PM](https://user-images.githubusercontent.com/45837622/127061979-76335796-0a96-484f-bab3-80eb236c6425.png)

NOTE:
If the animal has timeRemaining on its countdown, `do not` group it with other animals of the same animal id.
(If timeRemaining is != 0)

**Comment by soft-top-notch** [comment]
@CoryFlynn , According to my checking the code, I can find that the "timeRemaining" is always set to O.
![image](https://user-images.githubusercontent.com/48213961/127150383-642d6afd-5e06-4014-9da6-8deeed5d2062.png)
