### ISSUE TITLE
Feature: mapping from rarity to color

### ISSUE THREAD

**Issue by CoryFlynn** [zoo-labs/zoo#85]
## Feature
Implement the mapping from rarity to display color in the `My Account` page animal cards AND on the `Marketplace / My Zoo` animal cards.

Mapping:
'common' -> grey
'uncommon' -> green
'rare' -> blue
'super rare' -> purple
'epic' -> orange

`Marketplace:`
The animal rarity text on the marketplace cards should be mapped to the appropriate rarity color.
![Screen Shot 2021-07-27 at 12 27 09 PM](https://user-images.githubusercontent.com/45837622/127215772-713bf50b-3db3-4266-8a8b-1ca8190adc5a.png)

`My Account:`
The animal cards should be given a box shadow css attribute with a color that reflects the rarity of the animal.

**Comment by logohere** [comment]
![image](https://user-images.githubusercontent.com/69400476/127218366-7c2466d5-2c2f-4792-9464-5447176da0d3.png)

**Comment by itopmoon** [comment]
there is a rarity called `Legendary` but it's missing in the above mapping. @CoryFlynn please add a color for that. Thanks

**Comment by CoryFlynn** [comment]
![Screen Shot 2021-07-27 at 6 41 42 PM](https://user-images.githubusercontent.com/45837622/127250068-7235d233-195b-4735-a88c-05fbb8c007ec.png)
